name: 'Login azure'
description: 'Log into azure for a kubernetes deployment using helmfile'
inputs:
  client_id:  
    description: 'Azure client id'
    required: true
  tenant_id:
    description: 'Azure tenant id'  
    required: true
  subscription_id:
    description: 'Azure subscription id'
    required: true
  repository_name:
    description: 'Azure container registry name'
    required: true
outputs:
  helm_registry_token:
    description: 'Helm registry token'
    value: ${{ steps.get-helm-token.outputs.helm_registry_token }}
    
runs:
  using: "composite"
  steps:

    - name: Configure Azure Credentials
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client_id }}
        tenant-id: ${{ inputs.tenant_id }}
        subscription-id: ${{ inputs.subscription_id }}    

    - name: Get Helm Registry Token
      id: get-helm-token
      shell: bash
      env:
        ACR_NAME: ${{ inputs.repository_name }}
      run: |
        USER_NAME="00000000-0000-0000-0000-000000000000"
        PASSWORD=$(az acr login --name $ACR_NAME --expose-token --output tsv --query accessToken)
        echo "helm_registry_token=$PASSWORD" >> $GITHUB_OUTPUT
