name: 'Login azure'
description: 'Log into azure for a kubernetes deployment using helmfile'
inputs:
  creds:  
    required: true
  resource-group:  
    required: true
  cluster-name:  
    required: true
  repository-name:
    required: true
outputs:
  helmfile-creds:
    value: ${{ steps.set-helmfile.outputs.creds }}
    
runs:
  using: "composite"
  steps:

    - name: AZURE Setup / Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ inputs.creds }}
      
    - name: AZURE Setup / AKS Context
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ inputs.creds }}
        resource-group: ${{ inputs.resource-group }}
        cluster-name: ${{ inputs.cluster-name }}
    - id: set-helmfile
      shell: bash
      run: |
        export HELMFILE_CREDS=$(az acr login --name ${{ inputs.repository-name }} --expose-token --output tsv --query accessToken)
        echo "::set-output name=creds::$(echo $HELMFILE_CREDS)"